# config/elastic_apm.yml:

# Set service name - allowed characters: a-z, A-Z, 0-9, -, _ and space
# Defaults to the name of your Rails app
service_name: 'my-service'

# Use if APM Server requires a token
secret_token: '2zwedSuD9B0atKAouV'

# Set custom APM Server URL (default: http://localhost:8200)
server_url: 'https://8ad00e0711d149fbb56254c9f7851008.apm.us-west1.gcp.cloud.es.io:443'
