# config/elastic_apm.yml:

# Set service name - allowed characters: a-z, A-Z, 0-9, -, _ and space
# Defaults to the name of your Rails app
service_name: 'my-service'

# Use if APM Server requires a token
secret_token: 'kb2q3bkUOII80VKpgN'

# Set custom APM Server URL (default: http://localhost:8200)
server_url: 'https://a5e37b9cc9734709bda463c59cc3277f.apm.us-west1.gcp.cloud.es.io:443'
