# config/elastic_apm.yml:

# Set service name - allowed characters: a-z, A-Z, 0-9, -, _ and space
# Defaults to the name of your Rails app
service_name: 'my-service'

# Use if APM Server requires a token
secret_token: 'vAJuSighxg2YR1rwqZ'

# Set custom APM Server URL (default: http://localhost:8200)
server_url: 'https://f2c814f02d654836a43e47702f7107a1.apm.us-west1.gcp.cloud.es.io:443'
